version: '3.8'

services:
  
  app:
    build:
      context: ./docker/php-apache 
      dockerfile: Dockerfile
    container_name: myapp_web 
    ports:
      - "80:80" 
    volumes:
      - ./src:/var/www/html 
      
    environment:
      
      DB_CONNECTION: mysql
      DB_HOST: db 
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE:-myapp_db} 
      DB_USERNAME: ${MYSQL_USER:-root}
      DB_PASSWORD: ${MYSQL_PASSWORD:-password} 
      APP_ENV: local
      APP_DEBUG: true
    depends_on:
      - db 
    networks:
      - app-network

  
  db:
    image: mysql:8.0 
    container_name: myapp_db 
    ports:
      - "3307:3306" 
                             
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password} 
      MYSQL_DATABASE: ${MYSQL_DATABASE:-myapp_db} 
      
    volumes:
      - mysql-data:/var/lib/mysql 
    networks:
      - app-network


volumes:
  mysql-data:


networks:
  app-network:
    driver: bridge
